apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  project: default
  destination:
    namespace: infisical
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://dl.cloudsmith.io/public/infisical/helm-charts/helm/"
    chart: "infisical"
    targetRevision: "0.24.2"     # Example chart version (must be exact!)
    helm:
      releaseName: infisical
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
