apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  project: default
  destination:
    namespace: infisical
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/"
    chart: "infisical-standalone"
    targetRevision: "1.7.2"
    helm:
      releaseName: infisical
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
