apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
spec:
  destination:
    namespace: infisical
    server: 'https://kubernetes.default.svc'
  source:
    path: infisical-standalone
    repoURL: 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true